name: flutter_boids
description: A new Flutter project.

version: 1.0.0+4

environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
